# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'baseline' do
  # Pods for AppCenter
  pod 'AppCenter/Crashes', '~> 1.13.0'
  pod 'AppCenter/Analytics', '~> 1.13.0'
  pod 'AppCenterReactNativeShared', '~> 1.12.0'
end
